REPOSITORY_URL=https://github.com/BrianKipngetich1/fleet_management.git
MAIN_BRANCH=main
DEVELOP_BRANCH=develop
WORKING_BRANCH_PREFIXES=feature,fix,refactor,chore
KIT_VERSION=8f268ac
APP_NAME=fleet_management
MAIN_SITE=fleet_management.localhost
TEST_SITE=fleet_management-test.localhost
TEST_SITE_URL=http://fleet_management-test.localhost:8000
BENCH_ROOT=../..
BENCH_EXEC=
LOCALE_COUNTRY=Kenya
LOCALE_TIME_ZONE=Africa/Nairobi
LOCALE_CURRENCY=KES
LOCALE_DATE_FORMAT=dd/mm/yyyy
LOCALE_LANGUAGE=English
TEST_SITE_BUILD=bench fleet-test-site up --replace
SAMPLE_DATA_SEED=fleet_management.sample_data.seed
KIT_CHECK_SKIP=
