REPOSITORY_URL=https://github.com/BrianKipngetich1/fleet_management.git
MAIN_BRANCH=main
DEVELOP_BRANCH=develop
WORKING_BRANCH_PREFIXES=feature,fix,refactor,chore
KIT_VERSION=f4a3c20
APP_NAME=fleet_management
MAIN_SITE=fleet_management.localhost
TEST_SITE=fleet_management-test.localhost
TEST_SITE_URL=http://fleet_management-test.localhost:8000
BENCH_ROOT=../..
BENCH_EXEC=
LOCALE_COUNTRY=
LOCALE_TIME_ZONE=
LOCALE_CURRENCY=
LOCALE_DATE_FORMAT=
LOCALE_LANGUAGE=
